import turtle as f
import random
choice = ['magenta','white','black','blue','green']
f.clearscreen()
f.setup(400,400)
f.goto(-50,0)
f.fillcolor(random.choice(choice))
f.begin_fill()
for idx in range(3):
    f.forward(100)
    f.right(120)
f.end_fill()
f.goto(0,0)
f.fillcolor(random.choice(choice))
f.begin_fill()
f.circle(50)
f.end_fill()
f.penup()
f.goto(22,52)
f.pendown()
f.fillcolor(random.choice(choice))
f.begin_fill()
f.circle(40)
f.end_fill()
f.fillcolor(random.choice(choice))
f.begin_fill()
f.penup()
f.goto(22,42)
f.pendown()
f.circle(10)
f.end_fill()